{% set name = "tbump" %}
{% set version = "6.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tbump-{{ version }}.tar.gz
  sha256: 09a3c1f8a5266b152e3a9fb9182db8562a27cadaa20be18d82087b58b3405572

build:
  number: 0
  noarch: python
  entry_points:
    - tbump = tbump.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - attrs >=20.0.0
    - cli-ui >=0.10.3
    - docopt >=0.6.2
    - python >=3.6,<4.0
    - schema >=0.7.1
    - tomlkit >=0.5.8

test:
  imports:
    - tbump
  commands:
    - pip check
    - tbump --help
  requires:
    - pip

about:
  home: https://github.com/dmerejkowsky/tbump
  summary: Bump software releases
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
